server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exampleServer
    username: exampleUser
    password: examplePassword
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
  artemis:
    mode: embedded